'use strict'
module.exports =
    url: '/trade'
    path: 'buildings.trade'
    methods: [
        'add_to_market'
        'get_ship_summary'
        'get_ships'
        'get_prisoners'
        'get_plan_summary'
        'get_plans'
        'get_glyph_summary'
        'get_glyphs'
        'withdraw_from_market'
        'accept_from_market'
        'view_market'
        'view_my_market'
        'get_trade_ships'
        'get_waste_ships'
        'get_supply_ships'
        'view_supply_chains'
        'view_waste_chains'
        'create_supply_chain'
        'delete_supply_chain'
        'update_supply_chain'
        'update_waste_chain'
        'add_supply_ship_to_fleet'
        'add_waste_ship_to_fleet'
        'remove_supply_ship_from_fleet'
        'remove_waste_ship_from_fleet'
        'get_stored_resources'
        'push_items'
        'report_abuse'
    ]
