'use strict'
module.exports =
    url: '/parliament'
    path: 'modules.parliament'
    methods: [
        'view_laws'
        'view_propositions'
        'get_stars_in_jurisdiction'
        'get_bodies_for_star_in_jurisdiction'
        'get_mining_platforms_for_asteroid_in_jurisdiction'
        'cast_vote'
        'propose_writ'
        'propose_repeal_law'
        'propose_transfer_station_ownership'
        'propose_seize_star'
        'propose_rename_star'
        'propose_broadcast_on_network19'
        'propose_induct_member'
        'propose_expel_member'
        'propose_elect_new_leader'
        'propose_rename_asteroid'
        'propose_rename_uninhabited'
        'propose_members_only_mining_rights'
        'propose_evict_mining_platform'
        'propose_members_only_excavation'
        'propose_evict_excavator'
        'propose_members_only_colonization'
        'propose_neutralize_bhg'
        'propose_fire_bfg'
    ]
